export default {
  GET_LIST_NEW_BLOG: 'GET_LIST_NEW_BLOG',
  GET_LIST_NEW_BLOG_SUCCESS: 'GET_LIST_NEW_BLOG_SUCCESS',
  GET_LIST_SERIES: 'GET_LIST_SERIES',
  GET_LIST_SERIES_SUCCESS: 'GET_LIST_SERIES_SUCCESS'
};
