export default {
  GET_BOOKING_REMAIN: 'GET_BOOKING_REMAIN',
  GET_BOOKING_REMAIN_SUCCESS: 'GET_BOOKING_REMAIN_SUCCESS',
  GET_BOOKING_REMAIN_FAIL: 'GET_BOOKING_REMAIN_FAIL',

  GET_LIST_CALENDAR: 'GET_LIST_CALENDAR',
  GET_LIST_CALENDAR_SUCCESS: 'GET_LIST_CALENDAR_SUCCESS',
  GET_LIST_CALENDAR_FAIL: 'GET_LIST_CALENDAR_FAIL',

  BOOKING_CANLENDAR_KAIWA: 'BOOKING_CANLENDAR_KAIWA',
  BOOKING_CANLENDAR_KAIWA_SUCCESS: 'BOOKING_CANLENDAR_KAIWA_SUCCESS',
  BOOKING_CANLENDAR_KAIWA_FAIL: 'BOOKING_CANLENDAR_KAIWA_FAIL',

  CANCEL_CANLENDAR_KAIWA: 'CANCEL_CANLENDAR_KAIWA',
  CANCEL_CANLENDAR_KAIWA_SUCCESS: 'CANCEL_CANLENDAR_KAIWA_SUCCESS',
  CANCEL_CANLENDAR_KAIWA_FAIL: 'CANCEL_CANLENDAR_KAIWA_FAIL'
};
