export default {
  GET_LIST_COURSE: 'GET_LIST_COURSE',
  GET_LIST_COURSE_SUCCESS: 'GET_LIST_COURSE_SUCCESS',
  GET_LIST_COURSE_ERROR: 'GET_LIST_COURSE_ERROR',
  GET_LIST_COURSE_COMBO: 'GET_LIST_COURSE_COMBO',
  GET_LIST_COURSE_COMBO_SUCCESS: 'GET_LIST_COURSE_COMBO_SUCCESS',
  GET_COURSE: 'GET_COURSE',
  GET_COURSE_SUCCESS: 'GET_COURSE_SUCCESS',
  GET_STAGES: 'GET_STAGES',
  GET_STAGES_SUCCESS: 'GET_STAGES_SUCCESS'
};
