export default {
  GET_HOME_DATA: 'GET_HOME_DATA',
  GET_HOME_DATA_SUCCESS: 'GET_HOME_DATA_SUCCESS',
  GET_MY_IP: 'GET_MY_IP',
  GET_MY_IP_SUCCESS: 'GET_MY_IP_SUCCESS',
  GET_ADVERTISEMENT: 'GET_ADVERTISEMENT',
  GET_ADVERTISEMENT_SUCCESS: 'GET_ADVERTISEMENT_SUCCESS',
  GET_ADVERTISEMENT_FAILED: 'GET_ADVERTISEMENT_FAILED',
  GET_SETTING_SUCCESS: 'GET_SETTING_SUCCESS'
};
