export default {
  GET_LIST_LESSON: 'GET_LIST_LESSON',
  GET_LIST_LESSON_SUCCESS: 'GET_LIST_LESSON_SUCCESS',
  GET_LIST_LESSON_ERROR: 'GET_LIST_LESSON_ERROR',

  GET_LESSON_DETAIL: 'GET_LESSON_DETAIL',
  GET_LESSON_DETAIL_SUCCESS: 'GET_LESSON_DETAIL_SUCCESS',
  GET_LESSON_DETAIL_ERROR: 'GET_LESSON_DETAIL_ERROR',

  GET_LIST_LESSON_HOME: 'GET_LIST_LESSON_HOME',
  GET_LIST_LESSON_HOME_SUCCESS: 'GET_LIST_LESSON_HOME_SUCCESS',
  GET_LIST_LESSON_HOME_ERROR: 'GET_LIST_LESSON_HOME_ERROR',

  UPDATE_LESSON: 'UPDATE_LESSON',
  UPDATE_LIST_LESSON_SUCCESS: 'UPDATE_LIST_LESSON_SUCCESS',
  UPDATE_LIST_SPEC_LESSON_SUCCESS: 'UPDATE_LIST_SPEC_LESSON_SUCCESS',
  CHOOSE_SPECIAL_LESSON: 'CHOOSE_SPECIAL_LESSON',

  UPDATE_LESSON_NEW: 'UPDATE_LESSON_NEW',

  GET_LESSON_INFO: 'GET_LESSON_INFO',
  GET_LESSON_INFO_SUCCESS: 'GET_LESSON_INFO_SUCCESS',

  GET_VIDEO_QUESTION: 'GET_VIDEO_QUESTION',
  GET_VIDEO_QUESTION_SUCCESS: 'GET_VIDEO_QUESTION_SUCCESS',

  GET_LESSON_LUYEN_DE: 'GET_LESSON_LUYEN_DE',
  GET_LESSON_LUYEN_DE_SUCCESS: 'GET_LESSON_LUYEN_DE_SUCCESS',

  GET_RESULT_LUYEN_DE: 'GET_RESULT_LUYEN_DE',
  GET_RESULT_LUYEN_DE_SUCCESS: 'GET_RESULT_LUYEN_DE_SUCCESS',

  SUBMIT_ANSWER_RESULT: 'SUBMIT_ANSWER_RESULT',
  SUBMIT_ANSWER_RESULT_SUCCESS: 'SUBMIT_ANSWER_RESULT_SUCCESS'
};
