export default {
  GET_TESTING_ROOM: 'GET_TESTING_ROOM',
  GET_TESTING_ROOM_SUCCESS: 'GET_TESTING_ROOM_SUCCESS',
  UPDATE_TESTING_ROOM: 'UPDATE_TESTING_ROOM',
  GET_TESTING_CURRENT_TIME: 'GET_TESTING_CURRENT_TIME',
  GET_TESTING_CURRENT_TIME_SUCCESS: 'GET_TESTING_CURRENT_TIME_SUCCESS'
};
