export default {
  VERIFY_SESSION: 'VERIFY_SESSION',
  VERIFY_SESSION_SUCCESS: 'VERIFY_SESSION_SUCCESS',
  VERIFY_SESSION_FAILED: 'VERIFY_SESSION_FAILED',
  UPDATE_USER_SETTING: 'UPDATE_USER_SETTING',
  UPDATE_DEVICE: 'UPDATE_DEVICE',
  UPDATE_DEVICE_SUCCESS: 'UPDATE_DEVICE_SUCCESS'
};
