export default {
  VIDEO_DOWNLOAD_PROGRESS: 'VIDEO_DOWNLOAD_PROGRESS',
  VIDEO_DOWNLOAD_PROGRESS_SUCCESS: 'VIDEO_DOWNLOAD_PROGRESS_SUCCESS',
  VIDEO_DOWNLOAD_PROGRESS_FAIL: 'VIDEO_DOWNLOAD_PROGRESS_FAIL',
  STOP_VIDEO_DOWNLOAD: 'STOP_VIDEO_DOWNLOAD'
};
