export const LOGGING_IN = 'LOGGING_IN';
export const LOGGING_IN_SUCCESS = 'LOGGING_IN_SUCCESS';
export const LOGGING_IN_FAIL = 'LOGGING_IN_FAIL';

export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';

export const LOGIN_SOCIAL = 'LOGIN_SOCIAL';
export const LOGIN_SOCIAL_SUCCESS = 'LOGIN_SOCIAL_SUCCESS';
export const LOGIN_SOCIAL_FAIL = 'LOGIN_SOCIAL_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';
export const FETCHING_USER = 'FETCHING_USER';
export const FETCHING_USER_SUCCESS = 'FETCHING_USER_SUCCESS';
export const FETCHING_USER_FAIL = 'FETCHING_USER_FAIL';
export const UPDATING_USER_SUCCESS = 'UPDATING_USER_SUCCESS';
export const SERVER_VIDEO_SELECTED = 'SERVER_VIDEO_SELECTED';
export const LIST_SERVER = 'LIST_SERVER';
export const VIDEO_QUALITY = 'VIDEO_QUALITY';
export const SPEED_VIDEO = 'SPEED_VIDEO';
export const PERCENT_KAIWA = 'PERCENT_KAIWA';
export const UPDATE_TOTAL_NOTIFY = 'UPDATE_TOTAL_NOTIFY';
export const UPDATE_TOTAL_CONVERSATION = 'UPDATE_TOTAL_CONVERSATION';
export const LIST_OWNED = 'LIST_OWNED';
export const HIDE_INPUT_COMMENT = 'HIDE_INPUT_COMMENT';
export const SHOW_INPUT_COMMENT = 'SHOW_INPUT_COMMENT';
export const SAVE_SPEND_TIME = 'SAVE_SPEND_TIME';

export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const CHANGE_TEST_JLPT = 'CHANGE_TIME_TEST_JLPT';
export const GET_LIST_QUESTION = 'GET_LIST_QUESTION';
export const CHANGE_VIDEO_QUESTION = 'CHANGE_VIDEO_QUESTION';
export const IS_SLIDING = 'IS_SLIDING';
export const IS_SLIDING_COMPLETE = 'IS_SLIDING_COMPLETE';
